
##################################################################################################
# App service
##################################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-config
  namespace: default
data:
  config.map: config map test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}-deployment
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${APP_NAME}-service:latest
        command: ["/bin/sh"]
        args: ["-c", "/app/start.sh"]
        env:
          - name: CONFIG_MAP
            valueFrom:
              configMapKeyRef:
                name: ${APP_NAME}-config
                key: config.map
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: ${APP_NAME}-service-nodeport

# Note: Using NodePort you should open the sg of the node in order to access to it on the specified port
spec:
  type: NodePort
  selector: 
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
